### ISSUE TITLE
Is this still a spike?

### ISSUE THREAD

**Issue by decentral1se** [cotech/statically-generated-website#3]
Hey, I'd love to see the site converting over to Jekyll. I'd like to help, however, unless there is some idea that this might be a thing that is moving forward, maybe I'll just get in the way while people are just hacking around, doing spike things, testing, seeing what works etc.

If there's stuff to do, I'd like to see some issues created and I'll follow up!

**Comment by decentral1se** [comment]
Ah, I just found [the parking of the idea](https://www.loomio.org/d/FnHRkxCO/use-a-static-site-generator-for-the-cotech-website-and-host-on-github-pages%3Ffrom=40), so will close. Thanks anyway!

**Comment by floehopper** [comment]
@lwm Sorry for the slow reply. Yes, you're right - the idea got rejected in Loomio. [I've added a deprecation notice to the README](https://github.com/cotech/statically-generated-website/commit/f62e5472da37556fde073b2cb3ee0c98338c9850) to save other people the trouble.

**Comment by decentral1se** [comment]
All good! Thanks :)

**Comment by floehopper** [comment]
Further to this, I'm going to archive the repo now to help avoid confusion.
